### ISSUE TITLE
Segmentation fault with some case

### ISSUE THREAD

**Issue by yutozh** [jmyrberg/mknapsack#15]
This is my case:
```
std::vector<int> profits7 = {700, 600, 500, 400, 400, 300, 300, 300, 300, 300, 200, 200, 100, 100};
std::vector<int> weights7 = {7, 6, 5, 4, 4, 3, 3, 3, 3, 3, 2, 2, 1, 1};
std::vector<int> capacities7 = {8, 8, 8, 8, 8, 8};
```
Howerver, when I run the main.cpp, the program was stopped with "segmentation fault".

I debug the program and found the error was array out of bound in mtm_c.cpp:153. The variable 'il' is negative.
![image](https://user-images.githubusercontent.com/10933889/90954206-04d49980-e4a5-11ea-9e9c-d78d998e903e.png)

I don't quite understand  the meaning of variable "il". How to solve this problem?

**Comment by jmyrberg** [comment]
No more relevant, as using the original Fortran as source code, closing
